baseURL = "http://example.org/"
languageCode = "en-us"
title = "Personal Website"
copyright = "© {year}"

theme = "hugo-theme-codex" 

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "UA-173591822-1"

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2020"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/mohseenrm"
  email = "mailto:mohseen.mukaddam@gmail.com"
  facebook = "https://facebook.com/momo3300"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/mohseenrm"
  linkedin = "https://www.linkedin.com/in/mohseenrm/"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["GitHub", "LinkedIn", "Facebook", "Instagram", "Email"]

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "books"
  name = "books"
  title = "Books"
  url = "/book"
